
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('skills').del()
    .then(function () {
      // Inserts seed entries
      return knex('skills').insert([
        { name: 'Null', description: 'N/A', number_of_levels: -1 },
        { name: 'Poison Resistance', description: 'Reduces poison duration.', number_of_levels: 3 },
        { name: 'Paralysis Resistance', description: 'Reduces paralysis duration.', number_of_levels: 3 },
        { name: 'Sleep Resistance', description: 'Reduces sleep duration.', number_of_levels: 3 },
        { name: 'Stun Resistance', description: 'Reduces stun duration.', number_of_levels: 3 },
        { name: 'Muck Resistance', description: 'Reduces impairments to mobility while stuck in monster muck.', number_of_levels: 1 },
        { name: 'Blast Resistance', description: 'Grants protection against blastblight.', number_of_levels: 3 },
        { name: 'Bleeding Resistance', description: 'Grants protection against bleeding.', number_of_levels: 3 },
        { name: 'Iron Skin', description: 'Grants protection against Defense Down.', number_of_levels: 3 },
        { name: 'Earplugs', description: 'Grants protection from large monsters\' roars.', number_of_levels: 5 },
        { name: 'Windproof', description: 'Grants protection against wind pressure.', number_of_levels: 5 },
        { name: 'Tremor Resistance', description: 'Grants protection against ground tremors.', number_of_levels: 3 },
        { name: 'Dungmaster', description: 'Makes monsters hit with slinger dung pods more likely to run.', number_of_levels: 1 },
        { name: 'Effluvial Expert', description: 'Nullifies or reduces environmental damage in the Rotten Vale.', number_of_levels: 1 },
        { name: 'Heat Guard', description: 'Nullifies damage from heat.', number_of_levels: 1 },
        { name: 'Attack Boost', description: 'Increases attack power. Also improves affinity at higher levels.', number_of_levels: 7 },
        { name: 'Defense Boost', description: 'Increases defense. Level up to improve resistance as well.', number_of_levels: 7 },
        { name: 'Health Boost', description: 'Increases health.', number_of_levels: 3 },
        { name: 'Recovery Up', description: 'Increases the amount recovered when restoring health.', number_of_levels: 3 },
        { name: 'Recovery Speed', description: 'Speeds healing of recoverable damage (the red portion of the health guage).', number_of_levels: 3 },
        { name: 'Fire Resistance', description: 'Increases fire resistance. Also improves defense at higher levels.', number_of_levels: 3 },
        { name: 'Water Resistance', description: 'Increases water resistance. Also improves defense at higher levels.', number_of_levels: 3 },
        { name: 'Ice Resistance', description: 'Increases ice resistance. Also improves defense at higher levels.', number_of_levels: 3 },
        { name: 'Thunder Resistance', description: 'Increases thunder resistance. Also improves defense at higher levels.', number_of_levels: 3 },
        { name: 'Dragon Resistance', description: 'Increases dragon resistance. Also improves defense at higher levels.', number_of_levels: 3 },
        { name: 'Blight Resistance', description: 'Grants protection against all elemental blights.', number_of_levels: 3 },
        { name: 'Fire Attack', description: 'Increases fire element attack power. (Elemental attack power has a maximum limit.)', number_of_levels: 5 },
        { name: 'Water Attack', description: 'Increases water element attack power. (Elemental attack power has a maximum limit.)', number_of_levels: 5 },
        { name: 'Ice Attack', description: 'Increases ice element attack power. (Elemental attack power has a maximum limit.)', number_of_levels: 5 },
        { name: 'Thunder Attack', description: 'Increases thunder element attack power. (Elemental attack power has a maximum limit.)', number_of_levels: 5 },
        { name: 'Dragon Attack', description: 'Increases dragon element attack power. (Elemental attack power has a maximum limit.)', number_of_levels: 5 },
        { name: 'Poison Attack', description: 'Increases the rate of poison buildup. (Elemental buildup has a maximum limit.)', number_of_levels: 3 },
        { name: 'Paralysis Attack', description: 'Increases the rate of paralysis buildup. (Elemental buildup has a maximum limit.)', number_of_levels: 3 },
        { name: 'Sleep Attack', description: 'Increases the rate of sleep buildup. (Elemental buildup has a maximum limit.)', number_of_levels: 3 },
        { name: 'Blast Attack', description: 'Increases the rate of blast buildup. (Elemental buildup has a maximum limit.)', number_of_levels: 3 },
        { name: 'Piercing Shots', description: 'Increases the attack power of piercing ammo and Dragon Piercer.', number_of_levels: 1 },
        { name: 'Spread/Power Shots', description: 'Increases the attack power of spread ammo and power shot arrows.', number_of_levels: 1 },
        { name: 'Free Elem/Ammo Up', description: 'Unlocks your weapon\'s hidden element. Also increases bowgun loading capacity. (There is a cap to loading capacity.)', number_of_levels: 3 },
        { name: 'Critical Eye', description: 'Increases affinity.', number_of_levels: 7 },
        { name: 'Critical Boost', description: 'Increases the damage of critical hits.', number_of_levels: 3 },
        { name: 'Weakness Exploit', description: 'Increases the affinity of attacks that exploit a monster weak spot.', number_of_levels: 3 },
        { name: 'Focus', description: 'Increases the fill rate for weapons with gauges and the charge rate for weapons with charge attacks.', number_of_levels: 3 },
        { name: 'Power Prolonger', description: 'Allows long swords, dual blades, insect glaives, switch axes, and charge blades to stay powered up longer.', number_of_levels: 3 },
        { name: 'Handicraft', description: 'Extends the weapon sharpness gauge. However, it will not increase the gauge past its maximum.', number_of_levels: 5 },
        { name: 'Critical Draw', description: 'Increases affinity when performing draw attacks.', number_of_levels: 3 },
        { name: 'Partbreaker', description: 'Makes it easier to break or sever parts of large monsters.', number_of_levels: 3 },
        { name: 'Slugger', description: 'Makes it easier to stun monsters.', number_of_levels: 3 },
        { name: 'Stamina Thief', description: 'Increases certain attacks\' ability to exhaust monsters.', number_of_levels: 3 },
        { name: 'Master Mounter', description: 'Makes it easier to mount monsters.', number_of_levels: 1 },
        { name: 'Airborne', description: 'Increases the damage caused by jumping attacks.', number_of_levels: 1 },
        { name: 'Latent Power', description: 'Temporarily increases affinity and reduces stamina depletion when certain conditions are met.', number_of_levels: 5 },
        { name: 'Agitator', description: 'Increases attack power and affinity when large monsters become enraged.', number_of_levels: 5 },
        { name: 'Peak Performance', description: 'Increases attack when your health is full.', number_of_levels: 3 },
        { name: 'Heroics', description: 'Increases attack power and defense when health drops to 35% or lower.', number_of_levels: 5 },
        { name: 'Fortify', description: 'Increases your attack and defense every time you fall in battle. (This effect can stack twice.)', number_of_levels: 1 },
        { name: 'Resuscitate', description: 'Improves evasion and reduces stamina depletion when afflicted with abnormal status effects.', number_of_levels: 1 },
        { name: 'Horn Maestro', description: 'Increases the effect of hunting horn melodies.', number_of_levels: 1 },
        { name: 'Capacity Boost', description: 'Increases the gunlance\'s shell capacity and charge blade\'s phial capacity.', number_of_levels: 1 },
        { name: 'Special Ammo Boost', description: 'Increases the power of bowgun special ammo and Dragon Piercer.', number_of_levels: 2 },
        { name: 'Artillery', description: 'Strengthens explosive attacks like gunlance shells, Wyvern\'s Fire, charge blade phial attacks, and sticky ammo.', number_of_levels: 3 },
        { name: 'Heavy Artillery', description: 'Increases the firepower of ballistae and cannons.', number_of_levels: 2 },
        { name: 'Marathon Runner', description: 'Slows down stamina depletion for actions which continuously drain stamina (such as dashing).', number_of_levels: 3 },
        { name: 'Constitution', description: 'Reduces stamina depletion when performing stamina-draining moves such as evading, etc.', number_of_levels: 5 },
        { name: 'Leap of Faith', description: 'Allows you to do a dive-evade when facing towards large monsters, and extends the dive-evade distance.', number_of_levels: 1 },
        { name: 'Stamina Surge', description: 'Speeds up stamina recovery.', number_of_levels: 3 },
        { name: 'Hunger Resistance', description: 'Reduces maximum stamina depletion over time.', number_of_levels: 3 },
        { name: 'Evade Window', description: 'Extends the invulnerability period when evading.', number_of_levels: 5 },
        { name: 'Evade Extender', description: 'Increases evade distance.', number_of_levels: 3 },
        { name: 'Guard', description: 'Reduces knockbacks and stamina depletion when guarding.', number_of_levels: 5 },
        { name: 'Quick Sheath', description: 'Speeds up weapon sheathing.', number_of_levels: 3 },
        { name: 'Wide-Range', description: 'Allows the effects of certain items to also affect nearby allies.', number_of_levels: 5 },
        { name: 'Item Prolonger', description: 'Extends the duration of some item effects.', number_of_levels: 3 },
        { name: 'Free Meal', description: 'Gives you a predetermined chance of consuming a food or drink item for free.', number_of_levels: 1 },
        { name: 'Speed Eating', description: 'Increases meat-eating and item-consumption speed.', number_of_levels: 3 },
        { name: 'Speed Sharpening', description: 'Speeds up weapon sharpening when using a whetstone.', number_of_levels: 3 },
        { name: 'Bombardier', description: 'Increases the damage of explosive items.', number_of_levels: 3 },
        { name: 'Mushroomancer', description: 'Lets you digest mushrooms that would otherwise be inedible and gain their advantageous effects.', number_of_levels: 3 },
        { name: 'Master Fisher', description: 'Improves your skill at fishing.', number_of_levels: 1 },
        { name: 'Pro Transporter', description: 'Increases your speed while transporting items and decreases the likelihood of dropping them.', number_of_levels: 1 },
        { name: 'Master Gatherer', description: 'Allows you to gather more quickly, and also prevents attacks from knocking you back while gathering.', number_of_levels: 1 },
        { name: 'Honey Hunter', description: 'Increases the quantity of honey you receive when gathering in the field.', number_of_levels: 1 },
        { name: 'Carving Pro', description: 'Prevents knockback from attacks while carving.', number_of_levels: 1 },
        { name: 'Divine Blessing', description: 'Has a predetermined chance of reducing the damage you take.', number_of_levels: 3 },
        { name: 'Palico Rally', description: 'Powers up Palicoes.', number_of_levels: 5 },
        { name: 'Botanist', description: 'Increases the quantity of herbs and other consumable items you gather.', number_of_levels: 4 },
        { name: 'Geologist', description: 'Increases the number of times you can use a gathering point.', number_of_levels: 3 },
        { name: 'Maximum Might', description: 'Increases affinity when stamina is full.', number_of_levels: 3 },
        { name: 'Slinger Capacity', description: 'Increases the loading capacity for slinger ammo obtained in the field.', number_of_levels: 3 },
        { name: 'Stealth', description: 'Makes it easier for monsters to lose sight of you.', number_of_levels: 3 },
        { name: 'Flinch Free', description: 'Prevents knockbacks and other reactions to small damage.', number_of_levels: 3 },
        { name: 'Scoutfly Range Up', description: 'Expand your scoutflies\' detection range.', number_of_levels: 1 },
        { name: 'Speed Crawler', description: 'Increases movement speed while crouching.', number_of_levels: 1 },
        { name: 'Jump Master', description: 'Prevents attacks from knocking you back during a jump.', number_of_levels: 1 },
        { name: 'Sporepuff Expert', description: 'Recover health when using sporepuffs.', number_of_levels: 3 },
        { name: 'Aquatic Expert', description: 'Improves mobility in water.', number_of_levels: 3 },
        { name: 'Cliffhanger', description: 'Decreases stamina depletion when evading while clinging to walls or ivy.', number_of_levels: 1 },
        { name: 'Blindsider', description: 'Improves the effectiveness of flash attacks and items.', number_of_levels: 1 },
        { name: 'Scholar', description: 'Speeds up progress on research levels and special investigations. (Effect is applied at the quest results screen.)', number_of_levels: 1 },
        { name: 'Entomologist', description: 'Decreases the chances of destroying the bodies of small insect monsters, allowing them to be carved.', number_of_levels: 3 },
        { name: 'Effluvia Resistance', description: 'Gain a resistance to effluvial buildup.', number_of_levels: 3 },
        { name: 'Scenthound', description: 'Increases your scoutflies\' gauge fill rate when you find tracks and other traces left by monsters.', number_of_levels: 1 },
        { name: 'Forager\'s Luck', description: 'Increases the chance of finding rare gathering points.', number_of_levels: 1 },
        { name: 'Detector', description: 'Shows rare gathering points on the Wildlife Map.', number_of_levels: 1 },
        { name: 'Tool Specialist', description: 'Reduces the recharge time for specialized tools.', number_of_levels: 3 },
        { name: 'Affinity Sliding', description: 'Sliding increases your affinity for a short time.', number_of_levels: 1 },
        { name: 'Intimidator', description: 'Reduces the chances small monsters will attack after spotting you. (No effect on certain monsters.)', number_of_levels: 3 },
        { name: 'BBQ Master', description: 'Improves your skill at cooking meat.', number_of_levels: 1 },
        { name: 'Hasten Recovery', description: 'Regenerates your health as you continually attack a monster. Recovery varies by weapon.', number_of_levels: 0 },
        { name: 'Super Recovery', description: 'Allows recovery to exceed the red portion of the health gauge.', number_of_levels: 0 },
        { name: 'Poison Duration Up', description: 'Extends the duration of your poison\'s effect on monsters.', number_of_levels: 0 },
        { name: 'Adrenaline', description: 'Temporarily reduces stamina depletion when health is at 40% or lower.', number_of_levels: 0 },
        { name: 'Stamina Cap Up', description: 'Increases stamina cap.', number_of_levels: 0 },
        { name: 'Critical Element', description: 'Increases elemental damage (fire, water, thunder, ice, dragon) when landing critical hits.', number_of_levels: 0 },
        { name: 'Mind\'s Eye/Ballistics', description: 'Prevents attacks from being deflected. Also shortens the distance before ammo and arrows reach maximum power.', number_of_levels: 0 },
        { name: 'Bludgeoner', description: 'Raises attack as your weapon loses sharpness. Also boosts ranged weapon melee attacks and odds of stunning.', number_of_levels: 0 },
        { name: 'Non-elemental Boost', description: 'Powers up non-elemental weapons you have equipped.', number_of_levels: 0 },
        { name: 'Guard Up', description: 'Allows you to guard against ordinarily unblockable attacks.', number_of_levels: 0 },
        { name: 'Guts', description: 'Above a certain health threshold, you withstand an attack that would normally cart you (once only).', number_of_levels: 0 },
        { name: 'Master\'s Touch', description: 'Prevents your weapon from losing sharpness during critical hits.', number_of_levels: 0 },
        { name: 'Nullify Wind Pressure', description: 'Negates all wind pressure.', number_of_levels: 0 },
        { name: 'Razor Sharp/Spare Shot', description: 'Halves sharpness loss. For bows and bowguns, shots have a chance not to expend coatings or ammo.', number_of_levels: 0 },
        { name: 'Critical Status', description: 'Increases abnormal status effect damage (paralysis, poison, sleep, blast) when landing critical hits.', number_of_levels: 0 },
        { name: 'Good Luck', description: 'Good chance of increased quest rewards. (No effect when joining mid-quest.)', number_of_levels: 0 },
        { name: 'Bow Charge Plus', description: 'Increases max bow charge level by one.', number_of_levels: 0 },
        { name: 'Punishing Draw', description: 'Adds a stun effect to draw attacks and slightly increases attack power.', number_of_levels: 0 },
        { name: 'Protective Polish', description: 'Weapon sharpness does not decrease for a set time after sharpening.', number_of_levels: 0 },
      ]);
    })
    .then(function() {
      return knex('skill_descriptions').del()
        .then(function() {
          return knex('skill_descriptions').insert([
            { skill_id: 2, level: 1, description: 'Reduces the duration of poison by 30%.' },
            { skill_id: 2, level: 2, description: 'Reduces the duration of poison by 60%.' },
            { skill_id: 2, level: 3, description: 'Prevents poison.' },
            { skill_id: 3, level: 1, description: 'Reduces the duration of paralysis by 30%.' },
            { skill_id: 3, level: 2, description: 'Reduces the duration of paralysis by 60%.' },
            { skill_id: 3, level: 3, description: 'Prevents paralysis.' },
            { skill_id: 4, level: 1, description: 'Reduces the duration of sleep by 30%.' },
            { skill_id: 4, level: 2, description: 'Reduces the duration of sleep by 60%.' },
            { skill_id: 4, level: 3, description: 'Prevents sleep.' },
            { skill_id: 5, level: 1, description: 'Reduces the duration of stun by 30%.' },
            { skill_id: 5, level: 2, description: 'Reduces the duration of stun by 60%.' },
            { skill_id: 5, level: 3, description: 'Prevents stun.' },
            { skill_id: 6, level: 1, description: 'Reduces limits on movement speed and evasion.' },
            { skill_id: 7, level: 1, description: 'Delays blastblight and reduces blast damage.' },
            { skill_id: 7, level: 2, description: 'Greatly delays blastblight and greatly reduces blast damage.' },
            { skill_id: 7, level: 3, description: 'Prevents blastblight.' },
            { skill_id: 8, level: 1, description: 'Reduces damage while bleeding.' },
            { skill_id: 8, level: 2, description: 'Greatly reduces damage while bleeding.' },
            { skill_id: 8, level: 3, description: 'Prevents bleeding.' },
            { skill_id: 9, level: 1, description: 'Reduces the duration of Defense Down by 30%.' },
            { skill_id: 9, level: 2, description: 'Reduces the duration of Defense Down by 60%.' },
            { skill_id: 9, level: 3, description: 'Prevents Defense Down.' },
            { skill_id: 10, level: 1, description: 'Slightly reduces the effects of weak monster roars.' },
            { skill_id: 10, level: 2, description: 'Reduces the effects of weak monster roars.' },
            { skill_id: 10, level: 3, description: 'Nullifies weak monster roars.' },
            { skill_id: 10, level: 4, description: 'Nullifies weak monster roars and reduces the effects of strong monster roars.' },
            { skill_id: 10, level: 5, description: 'Nullifies weak and strong monster roars.' },
            { skill_id: 11, level: 1, description: 'Slightly reduces the effects of minor wind pressure.' },
            { skill_id: 11, level: 2, description: 'Reduces the effects of minor wind pressure.' },
            { skill_id: 11, level: 3, description: 'Negates minor wind pressure.' },
            { skill_id: 11, level: 4, description: 'Negates minor wind pressure and reduces the effects of major wind pressure.' },
            { skill_id: 11, level: 5, description: 'Negates minor and major wind pressure.' },
            { skill_id: 12, level: 1, description: 'Nullifies minor ground tremors.' },
            { skill_id: 12, level: 2, description: 'Nullifies minor ground tremors and reduces the effects of major ground tremors.' },
            { skill_id: 12, level: 3, description: 'Nullifies minor and major ground tremors.' },
            { skill_id: 13, level: 1, description: 'Makes slinger dung pods more effective at making monsters run away.' },
            { skill_id: 14, level: 1, description: 'Nullifies damage from effluvia and reduces damage from acids.' },
            { skill_id: 15, level: 1, description: 'Nullifies heat damage.' },
            { skill_id: 16, level: 1, description: 'Attack +3' },
            { skill_id: 16, level: 2, description: 'Attack +6' },
            { skill_id: 16, level: 3, description: 'Attack +9' },
            { skill_id: 16, level: 4, description: 'Attack +12\nAffinity +5%' },
            { skill_id: 16, level: 5, description: 'Attack +15\nAffinity +5%' },
            { skill_id: 16, level: 6, description: 'Attack +18\nAffinity +5%' },
            { skill_id: 16, level: 7, description: 'Attack +21\nAffinity +5%' },
            { skill_id: 17, level: 1, description: 'Defense +5' },
            { skill_id: 17, level: 2, description: 'Defense +10' },
            { skill_id: 17, level: 3, description: 'Defense +15' },
            { skill_id: 17, level: 4, description: 'Defense +20\nAll Elemental Resistances +3' },
            { skill_id: 17, level: 5, description: 'Defense +25\nAll Elemental Resistances +3' },
            { skill_id: 17, level: 6, description: 'Defense +30\nAll Elemental Resistances +3' },
            { skill_id: 17, level: 7, description: 'Defense +35\nAll Elemental Resistances +3' },
            { skill_id: 18, level: 1, description: 'Health +15' },
            { skill_id: 18, level: 2, description: 'Health +30' },
            { skill_id: 18, level: 3, description: 'Health +50' },
            { skill_id: 19, level: 1, description: 'Recovery +10%' },
            { skill_id: 19, level: 2, description: 'Recovery +20%' },
            { skill_id: 19, level: 3, description: 'Recovery +30%' },
            { skill_id: 20, level: 1, description: 'Doubles the speed at which you heal recoverable damage.' },
            { skill_id: 20, level: 2, description: 'Triples the speed at which you heal recoverable damage.' },
            { skill_id: 20, level: 3, description: 'Quadruples the speed at which you heal recoverable damage.' },
            { skill_id: 21, level: 1, description: 'Fire resistance +6' },
            { skill_id: 21, level: 2, description: 'Fire resistance +12' },
            { skill_id: 21, level: 3, description: 'Fire resistance +20\nDefense +10' },
            { skill_id: 22, level: 1, description: 'Water resistance +6' },
            { skill_id: 22, level: 2, description: 'Water resistance +12' },
            { skill_id: 22, level: 3, description: 'Water resistance +20\nDefense +10' },
            { skill_id: 23, level: 1, description: 'Ice resistance +6' },
            { skill_id: 23, level: 2, description: 'Ice resistance +12' },
            { skill_id: 23, level: 3, description: 'Ice resistance +20\nDefense +10' },
            { skill_id: 24, level: 1, description: 'Thunder resistance +6' },
            { skill_id: 24, level: 2, description: 'Thunder resistance +12' },
            { skill_id: 24, level: 3, description: 'Thunder resistance +20\nDefense +10' },
            { skill_id: 25, level: 1, description: 'Dragon resistance +6' },
            { skill_id: 25, level: 2, description: 'Dragon resistance +12' },
            { skill_id: 25, level: 3, description: 'Dragon resistance +20\nDefense +10' },
            { skill_id: 26, level: 1, description: 'Reduces the duration of all elemental blights by 30%.' },
            { skill_id: 26, level: 2, description: 'Reduces the duration of all elemental blights by 60%.' },
            { skill_id: 26, level: 3, description: 'Nullifies all elemental blights.' },
            { skill_id: 27, level: 1, description: 'Fire attack +30' },
            { skill_id: 27, level: 2, description: 'Fire attack +60' },
            { skill_id: 27, level: 3, description: 'Fire attack +100' },
            { skill_id: 27, level: 4, description: 'Fire attack +5%\nBonus: +100' },
            { skill_id: 27, level: 5, description: 'Fire attack +10%\nBonus: +100' },
            { skill_id: 28, level: 1, description: 'Water attack +30' },
            { skill_id: 28, level: 2, description: 'Water attack +60' },
            { skill_id: 28, level: 3, description: 'Water attack +100' },
            { skill_id: 28, level: 4, description: 'Water attack +5%\nBonus: +100' },
            { skill_id: 28, level: 5, description: 'Water attack +10%\nBonus: +100' },
            { skill_id: 29, level: 1, description: 'Ice attack +30' },
            { skill_id: 29, level: 2, description: 'Ice attack +60' },
            { skill_id: 29, level: 3, description: 'Ice attack +100' },
            { skill_id: 29, level: 4, description: 'Ice attack +5%\nBonus: +100' },
            { skill_id: 29, level: 5, description: 'Ice attack +10%\nBonus: +100' },
            { skill_id: 30, level: 1, description: 'Thunder attack +30' },
            { skill_id: 30, level: 2, description: 'Thunder attack +60' },
            { skill_id: 30, level: 3, description: 'Thunder attack +100' },
            { skill_id: 30, level: 4, description: 'Thunder attack +5%\nBonus: +100' },
            { skill_id: 30, level: 5, description: 'Thunder attack +10%\nBonus: +100' },
            { skill_id: 31, level: 1, description: 'Dragon attack +30' },
            { skill_id: 31, level: 2, description: 'Dragon attack +60' },
            { skill_id: 31, level: 3, description: 'Dragon attack +100' },
            { skill_id: 31, level: 4, description: 'Dragon attack +5%\nBonus: +100' },
            { skill_id: 31, level: 5, description: 'Dragon attack +10%\nBonus: +100' },
            { skill_id: 32, level: 1, description: 'Poison buildup +5%\nBonus: +10' },
            { skill_id: 32, level: 2, description: 'Poison buildup +10%\nBonus: +10' },
            { skill_id: 32, level: 3, description: 'Poison buildup +20%\nBonus: +10' },
            { skill_id: 33, level: 1, description: 'Paralysis buildup +5%\nBonus: +10' },
            { skill_id: 33, level: 2, description: 'Paralysis buildup +10%\nBonus: +10' },
            { skill_id: 33, level: 3, description: 'Paralysis buildup +20%\nBonus: +10' },
            { skill_id: 34, level: 1, description: 'Sleep buildup +5%\nBonus: +10' },
            { skill_id: 34, level: 2, description: 'Sleep buildup +10%\nBonus: +10' },
            { skill_id: 34, level: 3, description: 'Sleep buildup +20%\nBonus: +10' },
            { skill_id: 35, level: 1, description: 'Blast buildup +5%\nBonus: +10' },
            { skill_id: 35, level: 2, description: 'Blast buildup +10%\nBonus: +10' },
            { skill_id: 35, level: 3, description: 'Blast buildup +20%\nBonus: +10' },
            { skill_id: 36, level: 1, description: 'Increases the power of piercing ammo and Dragon Piercer.' },
            { skill_id: 37, level: 1, description: 'Increases the power of spread ammo and power shot arrows.' },
            { skill_id: 38, level: 1, description: 'Draws out 33% of hidden element and expands clip size for some ammo.' },
            { skill_id: 38, level: 2, description: 'Draws out 66% of hidden element and expands clip size for many ammo.' },
            { skill_id: 38, level: 3, description: 'Draws out 100% of hidden element and expands clip size for most ammo.' },
            { skill_id: 39, level: 1, description: 'Affinity +3%' },
            { skill_id: 39, level: 2, description: 'Affinity +6%' },
            { skill_id: 39, level: 3, description: 'Affinity +10%' },
            { skill_id: 39, level: 4, description: 'Affinity +15%' },
            { skill_id: 39, level: 5, description: 'Affinity +20%' },
            { skill_id: 39, level: 6, description: 'Affinity +25%' },
            { skill_id: 39, level: 7, description: 'Affinity +30%' },
            { skill_id: 40, level: 1, description: 'Increases damage dealt by critical hits by 30%.' },
            { skill_id: 40, level: 2, description: 'Increases damage dealt by critical hits by 35%.' },
            { skill_id: 40, level: 3, description: 'Increases damage dealt by critical hits by 40%.' },
            { skill_id: 41, level: 1, description: 'Attacks that hit weak spots have 15% increased affinity.' },
            { skill_id: 41, level: 2, description: 'Attacks that hit weak spots have 30% increased affinity.' },
            { skill_id: 41, level: 3, description: 'Attacks that hit weak spots have 50% increased affinity.' },
            { skill_id: 42, level: 1, description: 'Increases gauge fill rate by 5% and reduces charge times by 5%.' },
            { skill_id: 42, level: 2, description: 'Increases gauge fill rate by 10% and reduces charge times by 10%.' },
            { skill_id: 42, level: 3, description: 'Increases gauge fill rate by 20% and reduces charge times by 20%.' },
            { skill_id: 43, level: 1, description: 'Bonus duration +10%' },
            { skill_id: 43, level: 2, description: 'Bonus duration +20%' },
            { skill_id: 43, level: 3, description: 'Bonus duration +30%' },
            { skill_id: 44, level: 1, description: 'Weapon sharpness +10' },
            { skill_id: 44, level: 2, description: 'Weapon sharpness +20' },
            { skill_id: 44, level: 3, description: 'Weapon sharpness +30' },
            { skill_id: 44, level: 4, description: 'Weapon sharpness +40' },
            { skill_id: 44, level: 5, description: 'Weapon sharpness +50' },
            { skill_id: 45, level: 1, description: 'Draw attack affinity +30%' },
            { skill_id: 45, level: 2, description: 'Draw attack affinity +60%' },
            { skill_id: 45, level: 3, description: 'Draw attack affinity +100%' },
            { skill_id: 46, level: 1, description: 'Part damage +10%' },
            { skill_id: 46, level: 2, description: 'Part damage +20%' },
            { skill_id: 46, level: 3, description: 'Part damage +30%' },
            { skill_id: 47, level: 1, description: 'Stun power +10%' },
            { skill_id: 47, level: 2, description: 'Stun power +20%' },
            { skill_id: 47, level: 3, description: 'Stun power +30%' },
            { skill_id: 48, level: 1, description: 'Exhaust power +10%' },
            { skill_id: 48, level: 2, description: 'Exhaust power +20%' },
            { skill_id: 48, level: 3, description: 'Exhaust power +30%' },
            { skill_id: 49, level: 1, description: 'Makes it easier to mount monsters and down mounted monsters.' },
            { skill_id: 50, level: 1, description: 'Jumping attack power +10%' },
            { skill_id: 51, level: 1, description: 'While active, increases affinity by 10% and reduces stamina depletion by 10%.' },
            { skill_id: 51, level: 2, description: 'While active, increases affinity by 20% and reduces stamina depletion by 10%.' },
            { skill_id: 51, level: 3, description: 'While active, increases affinity by 30% and reduces stamina depletion by 30%.' },
            { skill_id: 51, level: 4, description: 'While active, increases affinity by 40% and reduces stamina depletion by 30%.' },
            { skill_id: 51, level: 5, description: 'While active, increases affinity by 50% and reduces stamina depletion by 50%.' },
            { skill_id: 52, level: 1, description: 'While active, grants attack +4 and increases affinity by 3%.' },
            { skill_id: 52, level: 2, description: 'While active, grants attack +8 and increases affinity by 6%.' },
            { skill_id: 52, level: 3, description: 'While active, grants attack +12 and increases affinity by 9%.' },
            { skill_id: 52, level: 4, description: 'While active, grants attack +16 and increases affinity by 12%.' },
            { skill_id: 52, level: 5, description: 'While active, grants attack +20 and increases affinity by 15%.' },
            { skill_id: 53, level: 1, description: 'While active, grants attack +5.' },
            { skill_id: 53, level: 2, description: 'While active, grants attack +10.' },
            { skill_id: 53, level: 3, description: 'While active, grants attack +20.' },
            { skill_id: 54, level: 1, description: 'While active, increases attack power by 5% and increases defense by 15 points.' },
            { skill_id: 54, level: 2, description: 'While active, increases attack power by 10% and increases defense by 20 points.' },
            { skill_id: 54, level: 3, description: 'While active, increases attack power by 15% and increases defense by 25 points.' },
            { skill_id: 54, level: 4, description: 'While active, increases attack power by 20% and increases defense by 30 points.' },
            { skill_id: 54, level: 5, description: 'While active, increases attack power by 30% and increases defense by 40 points.' },
            { skill_id: 55, level: 1, description: 'Increases attack by 10% and defense by 15% with each use.' },
            { skill_id: 56, level: 1, description: 'While active, greatly improves evasion invulnerability time and reduces stamina depletion.' },
            { skill_id: 57, level: 1, description: 'Extends melody effect duration and increases health recovery.' },
            { skill_id: 58, level: 1, description: 'Loading capacity +1' },
            { skill_id: 59, level: 1, description: 'Increases the power of bowgun special ammo and Dragon Piercer by 10%.' },
            { skill_id: 59, level: 2, description: 'Increases the power of bowgun special ammo and Dragon Piercer by 20%.' },
            { skill_id: 60, level: 1, description: 'Increases power of each attack by 10% and reduces Wyvern\'s Fire cooldown by 15%.' },
            { skill_id: 60, level: 2, description: 'Increases power of each attack by 20% and reduces Wyvern\'s Fire cooldown by 30%.' },
            { skill_id: 60, level: 3, description: 'Increases power of each attack by 30% and reduces Wyvern\'s Fire cooldown by 50%.' },
            { skill_id: 61, level: 1, description: 'Firepower +10%' },
            { skill_id: 61, level: 2, description: 'Firepower +20%' },
            { skill_id: 62, level: 1, description: 'Reduces continuous stamina depletion by 15%.' },
            { skill_id: 62, level: 2, description: 'Reduces continuous stamina depletion by 30%.' },
            { skill_id: 62, level: 3, description: 'Reduces continuous stamina depletion by 50%.' },
            { skill_id: 63, level: 1, description: 'Reduces fixed stamina depletion by 10%.' },
            { skill_id: 63, level: 2, description: 'Reduces fixed stamina depletion by 20%.' },
            { skill_id: 63, level: 3, description: 'Reduces fixed stamina depletion by 30%.' },
            { skill_id: 63, level: 4, description: 'Reduces fixed stamina depletion by 40%.' },
            { skill_id: 63, level: 5, description: 'Reduces fixed stamina depletion by 50%.' },
            { skill_id: 64, level: 1, description: 'Enables Leap of Faith.' },
            { skill_id: 65, level: 1, description: 'Stamina recovery speed +10%' },
            { skill_id: 65, level: 2, description: 'Stamina recovery speed +20%' },
            { skill_id: 65, level: 3, description: 'Stamina recovery speed +30%' },
            { skill_id: 66, level: 1, description: 'Extends the time until your stamina cap decreases by 30%.' },
            { skill_id: 66, level: 2, description: 'Extends the time until your stamina cap decreases by 60%.' },
            { skill_id: 66, level: 3, description: 'Prevents your stamina cap from decreasing.' },
            { skill_id: 67, level: 1, description: 'Very slightly increases invulnerability window.' },
            { skill_id: 67, level: 2, description: 'Slightly increases invulnerability window.' },
            { skill_id: 67, level: 3, description: 'Increases invulnerability window.' },
            { skill_id: 67, level: 4, description: 'Greatly increases invulnerability window.' },
            { skill_id: 67, level: 5, description: 'Massively increases invulnerability window.' },
            { skill_id: 68, level: 1, description: 'Slightly extends evasion distance.' },
            { skill_id: 68, level: 2, description: 'Extends evasion distance.' },
            { skill_id: 68, level: 3, description: 'Greatly extends evasion distance.' },
            { skill_id: 69, level: 1, description: 'Very slightly decreases the impact of attacks.' },
            { skill_id: 69, level: 2, description: 'Slightly decreases the impact of attacks and reduces stamina depletion by 15%.' },
            { skill_id: 69, level: 3, description: 'Greatly decreases the impact of attacks and reduces stamina depletion by 15%.' },
            { skill_id: 69, level: 4, description: 'Greatly decreases the impact of attacks and reduces stamina depletion by 30%.' },
            { skill_id: 69, level: 5, description: 'Massively decreases the impact of attacks and reduces stamina depletion by 50%.' },
            { skill_id: 70, level: 1, description: 'Slightly increases sheathing speed.' },
            { skill_id: 70, level: 2, description: 'Moderately increases sheathing speed.' },
            { skill_id: 70, level: 3, description: 'Greatly increases sheathing speed.' },
            { skill_id: 71, level: 1, description: 'Items affect nearby allies with 33% of their efficacy.' },
            { skill_id: 71, level: 2, description: 'Items affect nearby allies in a wider radius with 33% of their efficacy.' },
            { skill_id: 71, level: 3, description: 'Items affect nearby allies in a wider radius with 66% of their efficacy.' },
            { skill_id: 71, level: 4, description: 'Items affect nearby allies in a much wider radius with 66% of their efficacy.' },
            { skill_id: 71, level: 5, description: 'Items affect nearby allies in a much wider radius with full efficacy.' },
            { skill_id: 72, level: 1, description: 'Item effect duration +10%' },
            { skill_id: 72, level: 2, description: 'Item effect duration +25%' },
            { skill_id: 72, level: 3, description: 'Item effect duration +50%' },
            { skill_id: 73, level: 1, description: 'Activates 25% of the time.' },
            { skill_id: 74, level: 1, description: 'Slightly increases item use speed.' },
            { skill_id: 74, level: 2, description: 'Moderately increases item use speed.' },
            { skill_id: 74, level: 3, description: 'Greatly increases item use speed.' },
            { skill_id: 75, level: 1, description: 'Removes one cycle from the sharpening process.' },
            { skill_id: 75, level: 2, description: 'Removes two cycles from the sharpening process.' },
            { skill_id: 75, level: 3, description: 'Removes three cycles from the sharpening process.' },
            { skill_id: 76, level: 1, description: 'Explosive power +10%' },
            { skill_id: 76, level: 2, description: 'Explosive power +20%' },
            { skill_id: 76, level: 3, description: 'Explosive power +30%' },
            { skill_id: 77, level: 1, description: 'Lets you digest blue mushrooms and toadstools.' },
            { skill_id: 77, level: 2, description: 'Additionally lets you digest nitroshrooms and parashrooms.' },
            { skill_id: 77, level: 3, description: 'Additionally lets you digest mandragoras, devil\'s bligh, and exciteshrooms.' },
            { skill_id: 78, level: 1, description: 'Increases the time window for reeling in fish, and makes it easier to catch large fish.' },
            { skill_id: 79, level: 1, description: 'Increases movement speed while transporting and reduces downtime on landings.' },
            { skill_id: 80, level: 1, description: 'Speeds up gathering and prevents knockbacks while gathering.' },
            { skill_id: 81, level: 1, description: 'One extra honey per gather.' },
            { skill_id: 82, level: 1, description: 'Prevents knockback while carving.' },
            { skill_id: 83, level: 1, description: 'While active, reduces damage taken by 15%.' },
            { skill_id: 83, level: 2, description: 'While active, reduces damage taken by 30%.' },
            { skill_id: 83, level: 3, description: 'While active, reduces damage taken by 50%.' },
            { skill_id: 84, level: 1, description: 'Increases Palico attack power and defense by 5%.' },
            { skill_id: 84, level: 2, description: 'Increases Palico attack power and defense by 10%.' },
            { skill_id: 84, level: 3, description: 'Increases Palico attack power and defense by 15%.' },
            { skill_id: 84, level: 4, description: 'Increases Palico attack power and defense by 20%.' },
            { skill_id: 84, level: 5, description: 'Increases Palico attack power and defense by 25%.' },
            { skill_id: 85, level: 1, description: 'One extra consumable herb item per gather.' },
            { skill_id: 85, level: 2, description: 'One extra consumable herb, fruit, nut, or seed item per gather.' },
            { skill_id: 85, level: 3, description: 'One extra consumable herb, fruit, nut, seed, or insect item per gather.' },
            { skill_id: 85, level: 4, description: 'One extra consumable herb, fruit, nut, seed, insect, or mushroom item per gather.' },
            { skill_id: 86, level: 1, description: 'Allows you to gather one extra time from bonepiles.' },
            { skill_id: 86, level: 2, description: 'Allows you to gather one extra time from bonepiles and special item gathering points.' },
            { skill_id: 86, level: 3, description: 'Allows you to gather one extra time from bonepiles, gathering points, and mining outcrops.' },
            { skill_id: 87, level: 1, description: 'While active, increases affinity by 10%.' },
            { skill_id: 87, level: 2, description: 'While active, increases affinity by 20%.' },
            { skill_id: 87, level: 3, description: 'While active, increases affinity by 30%.' },
            { skill_id: 88, level: 1, description: 'Increases the loading capacity for slinger ammo collected from the ground or plants.' },
            { skill_id: 88, level: 2, description: 'In addition, increases the loading capacity for some slinger ammo dropped by monsters.' },
            { skill_id: 88, level: 3, description: 'In addition, increases the loading capacity for all slinger ammo dropped by monsters.' },
            { skill_id: 89, level: 1, description: 'Makes it slightly easier for monsters to lose sight of you.' },
            { skill_id: 89, level: 2, description: 'Makes it moderately easier for monsters to lose sight of you.' },
            { skill_id: 89, level: 3, description: 'Makes it much easier for monsters to lose sight of you.' },
            { skill_id: 90, level: 1, description: 'Prevents knockbacks.' },
            { skill_id: 90, level: 2, description: 'Prevents standard knockbacks. Tripping is reduced to a knockback instead.' },
            { skill_id: 90, level: 3, description: 'Prevents knockbacks and tripping.' },
            { skill_id: 91, level: 1, description: 'Expands your scoutflies\' detection range.' },
            { skill_id: 92, level: 1, description: 'Increases movement speed while crouching.' },
            { skill_id: 93, level: 1, description: 'Negates knockback during jumps.' },
            { skill_id: 94, level: 1, description: 'Sporepuffs restore 20 health.' },
            { skill_id: 94, level: 2, description: 'Sporepuffs restore 35 health.' },
            { skill_id: 94, level: 3, description: 'Sporepuffs restore 60 health.' },
            { skill_id: 95, level: 1, description: 'Prevents water from slowing movement.' },
            { skill_id: 95, level: 2, description: 'Prevents water from slowing movement and improves evasion while in water.' },
            { skill_id: 95, level: 3, description: 'Prevents water from slowing movement and greatly improves evasion while in water.' },
            { skill_id: 96, level: 1, description: 'Reduces stamina depletion while climbing by 25%.' },
            { skill_id: 97, level: 1, description: 'Increases the success rate of flash effects.' },
            { skill_id: 98, level: 1, description: 'Speeds up progress on research levels and special investigations.' },
            { skill_id: 99, level: 1, description: 'Increases the chances of a corpse being left behind.' },
            { skill_id: 99, level: 2, description: 'Greatly increases the chances of a corpse being left behind.' },
            { skill_id: 99, level: 3, description: 'Makes it so corpses will always be left behind.' },
            { skill_id: 100, level: 1, description: 'Reduces effluvial buildup.' },
            { skill_id: 100, level: 2, description: 'Greatly reduces effluvial buildup.' },
            { skill_id: 100, level: 3, description: 'Prevents effluvial buildup.' },
            { skill_id: 101, level: 1, description: 'Increases gauge fill rate by 50%.' },
            { skill_id: 102, level: 1, description: 'Increases the likelihood of rare gathering points respawning.' },
            { skill_id: 103, level: 1, description: 'Marks rare sites on the wildlife map.' },
            { skill_id: 104, level: 1, description: 'Shortens time until reuse by 5%.' },
            { skill_id: 104, level: 2, description: 'Shortens time until reuse by 10%.' },
            { skill_id: 104, level: 3, description: 'Shortens time until reuse by 20%.' },
            { skill_id: 105, level: 1, description: 'Increases affinity by 30% for a short time after sliding.' },
            { skill_id: 106, level: 1, description: 'Discourages monsters from engaging you even if you\'ve been spotted' },
            { skill_id: 106, level: 2, description: 'Highly discourages monsters from engaging you even if you\'ve been spotted' },
            { skill_id: 106, level: 3, description: 'Prevents monsters from engaging you even if you\'ve been spotted.' },
            { skill_id: 107, level: 1, description: 'Makes it easier to cook well-done steaks.' },
          ]);
        });
    });
};
