
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('charms').del()
    .then(function () {
      // Inserts seed entries
      return knex('charms').insert([
        { name: 'Poison Charm', rarity: 3, max_level: 3, skill_1: 2 },
        { name: 'Attack Charm', rarity: 3, max_level: 3, skill_1: 16 },
        { name: 'Defense Charm', rarity: 3, max_level: 3, skill_1: 17 },
        { name: 'Paralysis Charm', rarity: 3, max_level: 3, skill_1: 3 },
        { name: 'Sleep Charm', rarity: 3, max_level: 3, skill_1: 4 },
        { name: 'Stun Charm', rarity: 3, max_level: 3, skill_1: 5 },
        { name: 'Windproof Charm', rarity: 3, max_level: 3, skill_1: 11 },
        { name: 'Health Charm', rarity: 3, max_level: 3, skill_1: 18 },
        { name: 'Recovery Charm', rarity: 3, max_level: 3, skill_1: 19 },
        { name: 'Fire Charm', rarity: 3, max_level: 3, skill_1: 21 },
        { name: 'Water Charm', rarity: 3, max_level: 3, skill_1: 22 },
        { name: 'Thunder Charm', rarity: 3, max_level: 3, skill_1: 24 },
        { name: 'Flood Charm', rarity: 3, max_level: 3, skill_1: 28 },
        { name: 'Shock Charm', rarity: 3, max_level: 3, skill_1: 30 },
        { name: 'Venom Charm', rarity: 3, max_level: 3, skill_1: 32 },
        { name: 'Immobilize Charm', rarity: 3, max_level: 3, skill_1: 33 },
        { name: 'Tranq Charm', rarity: 3, max_level: 3, skill_1: 34 },
        { name: 'KO Charm', rarity: 3, max_level: 3, skill_1: 47 },
        { name: 'Enervate Charm', rarity: 3, max_level: 3, skill_1: 48 },
        { name: 'Artillery Charm', rarity: 3, max_level: 3, skill_1: 60 },
        { name: 'Hungerless Charm', rarity: 3, max_level: 3, skill_1: 66 },
        { name: 'Ironside Charm', rarity: 3, max_level: 3, skill_1: 69 },
        { name: 'Friendship Charm', rarity: 3, max_level: 3, skill_1: 71 },
        { name: 'Extension Charm', rarity: 3, max_level: 3, skill_1: 72 },
        { name: 'Glutton\'s Charm', rarity: 3, max_level: 3, skill_1: 74 },
        { name: 'Blessing Charm', rarity: 3, max_level: 3, skill_1: 83 },
        { name: 'Rally Charm', rarity: 3, max_level: 3, skill_1: 84 },
        { name: 'Botany Charm', rarity: 3, max_level: 3, skill_1: 85 },
        { name: 'Geology Charm', rarity: 3, max_level: 3, skill_1: 86 },
        { name: 'Slinger Charm', rarity: 3, max_level: 3, skill_1: 88 },
        { name: 'Stealth Charm', rarity: 3, max_level: 3, skill_1: 89 },
        { name: 'Smoke Charm', rarity: 3, max_level: 3, skill_1: 94 },
        { name: 'Mirewalker Charm', rarity: 3, max_level: 3, skill_1: 95 },
        { name: 'Insect Charm', rarity: 3, max_level: 3, skill_1: 99 },
        { name: 'Intimidator Charm', rarity: 3, max_level: 3, skill_1: 106 },
        { name: 'Heavy Artillery Charm', rarity: 3, max_level: 2, skill_1: 61 },
        { name: 'Light Eater\'s Charm', rarity: 3, max_level: 1, skill_1: 73 },
        { name: 'Tracker Charm', rarity: 3, max_level: 1, skill_1: 101 },
        { name: 'Fortification Charm', rarity: 3, max_level: 1, skill_1: 55 },
        { name: 'Performer\'s Charm', rarity: 3, max_level: 1, skill_1: 57 },
        { name: 'Capacity Charm', rarity: 3, max_level: 1, skill_1: 58 },
        { name: 'Bleed Charm', rarity: 4, max_level: 3, skill_1: 8 },
        { name: 'Speed Heal Charm', rarity: 4, max_level: 3, skill_1: 20 },
        { name: 'Ice Charm', rarity: 4, max_level: 3, skill_1: 23 },
        { name: 'Blight Charm', rarity: 4, max_level: 3, skill_1: 26 },
        { name: 'Frost Charm', rarity: 4, max_level: 3, skill_1: 29 },
        { name: 'Master\'s Charm', rarity: 4, max_level: 3, skill_1: 39 },
        { name: 'Evasion Charm', rarity: 4, max_level: 3, skill_1: 67 },
        { name: 'Sheath Charm', rarity: 4, max_level: 3, skill_1: 70 },
        { name: 'Whetstone Charm', rarity: 4, max_level: 3, skill_1: 75 },
        { name: 'Blast Charm', rarity: 5, max_level: 3, skill_1: 7 },
        { name: 'Dragon Charm', rarity: 5, max_level: 3, skill_1: 25 },
        { name: 'Wyrmsbane Charm', rarity: 5, max_level: 3, skill_1: 31 },
        { name: 'Demolition Charm', rarity: 5, max_level: 3, skill_1: 35 },
        { name: 'Draw Charm', rarity: 5, max_level: 2, skill_1: 45 },
        { name: 'Trickshot Charm', rarity: 5, max_level: 2, skill_1: 59 },
        { name: 'Marathon Charm', rarity: 5, max_level: 2, skill_1: 62 },
        { name: 'Fitness Charm', rarity: 5, max_level: 3, skill_1: 63 },
        { name: 'Surge Charm', rarity: 5, max_level: 2, skill_1: 65 },
        { name: 'Leaping Charm', rarity: 5, max_level: 2, skill_1: 68 },
        { name: 'Bombardier Charm', rarity: 5, max_level: 3, skill_1: 76 },
        { name: 'Mushroom Charm', rarity: 5, max_level: 2, skill_1: 77 },
        { name: 'Awakening Charm', rarity: 5, max_level: 2, skill_1: 38 },
        { name: 'Handicraft Charm', rarity: 5, max_level: 3, skill_1: 44 },
        { name: 'Mud Puppy Charm', rarity: 5, max_level: 1, skill_1: 6, skill_2: 64 },
        { name: 'Trickshot Charm', rarity: 5, max_level: 1, skill_1: 13, skill_2: 97 },
        { name: 'Hunter\'s Life Charm', rarity: 5, max_level: 1, skill_1: 107, skill_2: 78 },
        { name: 'Procurer\'s Charm', rarity: 5, max_level: 1, skill_1: 79, skill_2: 81 },
        { name: 'Gatherer\'s Charm', rarity: 5, max_level: 1, skill_1: 80, skill_2: 82 },
        { name: 'Guard Charm', rarity: 6, max_level: 3, skill_1: 9 },
        { name: 'Earplugs Charm', rarity: 6, max_level: 3, skill_1: 10 },
        { name: 'Tremor Charm', rarity: 6, max_level: 2, skill_1: 12 },
        { name: 'Exploiter Charm', rarity: 6, max_level: 2, skill_1: 41 },
        { name: 'Focus Charm', rarity: 6, max_level: 2, skill_1: 42 },
        { name: 'Breaker Charm', rarity: 6, max_level: 2, skill_1: 46 },
        { name: 'Fury Charm', rarity: 6, max_level: 2, skill_1: 128 },
        { name: 'Grit Charm', rarity: 6, max_level: 2, skill_1: 54 },
        { name: 'Maintenance Charm', rarity: 6, max_level: 3, skill_1: 104 },
        { name: 'Power Charm', rarity: 7, max_level: 2, skill_1: 51 },
        { name: 'Challenger Charm', rarity: 7, max_level: 2, skill_1: 52 },
        { name: 'Unscathed Charm', rarity: 7, max_level: 2, skill_1: 53 },
        { name: 'Mighty Charm', rarity: 7, max_level: 2, skill_1: 87 },
        { name: 'Impact Charm', rarity: 7, max_level: 2, skill_1: 90 },
        { name: 'Miasma Charm', rarity: 7, max_level: 3, skill_1: 100 },
        { name: 'Normal Shots Charm', rarity: 7, max_level: 1, skill_1: 129 },
        { name: 'Clearmind Charm', rarity: 7, max_level: 1, skill_1: 15, skill_2: 14 },
        { name: 'Rider\'s Charm', rarity: 7, max_level: 1, skill_1: 49, skill_2: 93 },
        { name: 'Surveyor\'s Charm', rarity: 7, max_level: 1, skill_1: 91, skill_2: 98 },
        { name: 'Invigorate Charm', rarity: 8, max_level: 2, skill_1: 43 },
        { name: 'Geomancy Charm', rarity: 8, max_level: 1, skill_1: 102, skill_2: 103 },
      ]);
    });
};
